version: '3'
volumes:
  data-vol:

services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt/tomcat/latest/webapps"
    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_DATABASE: database
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.8.0.3


  tomcat:
    build: service
    depends_on:
      - builder
      - db
    ports: 
      - "8080:8080"
    volumes:
       - "data-vol:/opt/tomcat/webapps/"
    networks:
      vpcbr:
        ipv4_address: 10.8.0.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/29
         gateway: 10.8.0.1
